import { sortByLayer, validateLayers } from '../canvas/z-index-manager.js';

/**
 * @typedef {Object} Outfit
 * @property {string} id
 * @property {string} name
 * @property {import('./garment.js').Garment[]} garments
 * @property {string} [styleName] - AI-generated style label (e.g. "Smart Casual")
 * @property {number} [confidenceScore] - AI confidence 0-1
 * @property {string} [photoUrl] - Photorealistic daily look image URL (generated by renderer)
 * @property {Record<string, any>} [renderMetadata]
 */

/**
 * Creates a validated Outfit. Garments are sorted by z-index.
 * @param {{ id?: string, name: string, garments: import('./garment.js').Garment[], styleName?: string, confidenceScore?: number, photoUrl?: string, renderMetadata?: Record<string, any> }} data
 * @returns {Outfit}
 */
export function createOutfit(data) {
  const sorted = sortByLayer(data.garments);
  return {
    id: data.id || `outfit-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    name: data.name,
    garments: sorted,
    styleName: data.styleName,
    confidenceScore: data.confidenceScore,
    photoUrl: data.photoUrl,
    renderMetadata: data.renderMetadata,
  };
}

/**
 * Returns garments sorted ascending by z-index for rendering (bottom layer first).
 * @param {Outfit} outfit
 * @returns {import('./garment.js').Garment[]}
 */
export function getLayeredGarments(outfit) {
  return sortByLayer(outfit.garments);
}

/**
 * Validates an outfit's layer composition.
 * @param {Outfit} outfit
 * @returns {{ valid: boolean, errors: string[] }}
 */
export function validateOutfit(outfit) {
  return validateLayers(outfit.garments);
}
